version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
  app:
    image: felixindrawan-spatiallaser-backend
    ports:
      - 13000:1338